name: CI

on:
  push:
    branches: ["main"]
    tags: ["v*"]

  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: test build
        env:
          repo: ${{ github.repository }}
          sha: ${{ github.sha }}
        run: docker build . --file Dockerfile --tag ${repo}:${sha}-$(date +%s)

  publish-ghcr:
    needs: test
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      attestations: write
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token
      artifact-metadata: write
    env:
      REGISTRY: ghcr.io
      # IMAGE_NAME: ${{ github.repository }}
      IMAGE_NAME: "${{ github.repository_owner }}/aprsc"
    environment:
      name: ghcr.io Registry
      url: https://github.com/uiolee/aprsc-docker/pkgs/container/aprsc
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Get Git commit timestamps
        run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      - uses: docker/setup-qemu-action@v4
      - uses: docker/setup-buildx-action@v4

      - name: Log in to registry `${{ env.REGISTRY }}`
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: metadata
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build_push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.build_push.outputs.digest }}
          push-to-registry: true
